<?php 

$labels = array(
	'name' => _x( 'Configurator', 'Post Type General Name', 'advance-neon-product-designer' ),
	'singular_name' => _x( 'Configurator ', 'Post Type Singular Name', 'advance-neon-product-designer' ),
	'menu_name' => _x( 'APDS', 'Admin Menu text', 'advance-neon-product-designer' ),
	'name_admin_bar' => _x( 'Configurator ', 'Add New on Toolbar', 'advance-neon-product-designer' ),
	'archives' => __( 'Configurator  Archives', 'advance-neon-product-designer' ),
	'attributes' => __( 'Configurator  Attributes', 'advance-neon-product-designer' ),
	'parent_item_colon' => __( 'Parent Configurator :', 'advance-neon-product-designer' ),
	'all_items' => __( 'All APDS', 'advance-neon-product-designer' ),
	'add_new_item' => __( 'Add New Configurator ', 'advance-neon-product-designer' ),
	'add_new' => __( 'Add New Configurator', 'advance-neon-product-designer' ),
	'new_item' => __( 'New Configurator ', 'advance-neon-product-designer' ),
	'edit_item' => __( 'Edit Configurator ', 'advance-neon-product-designer' ),
	'update_item' => __( 'Update Configurator ', 'advance-neon-product-designer' ),
	'view_item' => __( 'View Configurator ', 'advance-neon-product-designer' ),
	'view_items' => __( 'View Configurator', 'advance-neon-product-designer' ),
	'search_items' => __( 'Search Configurator ', 'advance-neon-product-designer' ),
	'not_found' => __( 'Not found', 'advance-neon-product-designer' ),
	'not_found_in_trash' => __( 'Not found in Trash', 'advance-neon-product-designer' ),
	'featured_image' => __( 'Featured Image', 'advance-neon-product-designer' ),
	'set_featured_image' => __( 'Set featured image', 'advance-neon-product-designer' ),
	'remove_featured_image' => __( 'Remove featured image', 'advance-neon-product-designer' ),
	'use_featured_image' => __( 'Use as featured image', 'advance-neon-product-designer' ),
	'insert_into_item' => __( 'Insert into Configurator ', 'advance-neon-product-designer' ),
	'uploaded_to_this_item' => __( 'Uploaded to this Configurator ', 'advance-neon-product-designer' ),
	'items_list' => __( 'APDS list', 'advance-neon-product-designer' ),
	'items_list_navigation' => __( 'APDS list navigation', 'advance-neon-product-designer' ),
	'filter_items_list' => __( 'Filter APDS list', 'advance-neon-product-designer' ),
);
$args = array(
	'label' => __( 'Configurator ', 'advance-neon-product-designer' ),
	'description' => __( 'Advance Neon Product Designer By Qwerty Experts', 'advance-neon-product-designer' ),
	'labels' => $labels,
	'menu_icon' => '',
	'supports' => array('title'),
	'taxonomies' => array(),
	'public' => false,
	'show_ui' => true,
	'show_in_menu' => false,
	'menu_position' => 5,
	'show_in_admin_bar' => false,
	'show_in_nav_menus' => false,
	'can_export' => true,
	'has_archive' => false,
	'hierarchical' => false,
	'exclude_from_search' => true,
	'show_in_rest' => false,
	'publicly_queryable' => false,
	'capability_type' => 'post',
);
register_post_type( 'anpd-configurator', $args );